cloudquery/plugin-pb-go

- specs/spec_reader.go
- specs/spec_reader_test.go
Fixes https://github.com/cloudquery/cloudquery/issues/11178
> fix: Embedded content handling with newlines

- pb/destination/v1/arrow.go
- pb/source/v2/arrow.go
This moves byte encoding/decoding function to be under the right package/version (for old protocol) as they are part of the protocol and cannot change.
> feat: Add arrow schema encoding to v2

- pb/destination/v1/arrow.go
- pb/source/v2/arrow.go
Follow-up to https://github.com/cloudquery/plugin-pb-go/pull/26. We shouldn't introduce any new objects here and those helper function should only take care of encoding/decoding.
> fix: Update schema encoding/deocoding in v2

- pb/destination/v1/arrow.go
- pb/source/v2/arrow.go
Adds the required record encoding/decoding functions to destination v1 and sourcev2 protocol
> fix: Add record enc/dec to destv1 sourcev2

- managedplugin/plugin.go
Exposes a `ConnectionString` method that can be used to connect to the client via GRPC. It includes the protocol in the string so that GRPC clients can automatically infer the connection type.
> feat: Expose ConnectionString method in Client

- managedplugin/plugin.go
This fixes a race condition between the container coming up and the plugin server being up.
> fix: Wait for gRPC TCP connection in Docker registry

- managedplugin/options.go
- managedplugin/plugin.go
This is required to separate download and execute steps, will help with https://github.com/cloudquery/cloudquery/issues/13937
> feat: Add option `WithNoExec()` to skip executing of plugins

- managedplugin/download.go
> feat: Add more error handling to downloading Hub plugins

- managedplugin/download.go
- managedplugin/download_test.go
- managedplugin/options.go
- managedplugin/plugin.go
- managedplugin/plugin_test.go
Related to https://github.com/cloudquery/cloudquery-issues/issues/737 (internal issue).
This should unlock paid plugins downloads from the Hub. CLI PR coming in a bit
---
> feat: Allow passing an auth token when downloading Hub plugins

- managedplugin/plugin.go
Closes https://github.com/cloudquery/cloudquery/issues/15081
> fix: Add `unix://` to connection string for plugins from CloudQuery Hub

- managedplugin/download.go
Use `CLOUDQUERY_API_URL` for everything. Other consumers can now also use `managedplugin.APIBaseURL()`
Breaking compatibility very briefly (string becomes a func for a cq-internal functionality) so I'm not doing a `feat!`
> feat: Use and expose api url env variable

- go.mod
- go.sum
- managedplugin/download.go
Do the `application/json` request and get checksum + location.
> feat: Validate hub download checksums

- go.mod
- go.sum
- managedplugin/download.go
- managedplugin/download_test.go
- managedplugin/options.go
- managedplugin/plugin.go
Adding the ability to pass the `team_name` to the download. This will be passed in by the CLI as either the `team_name` in the user's saved configuration (i.e. `cloudquery switch` config) or the `team_name` associated with the API key being used.
Ref: https://github.com/cloudquery/cloudquery-issues/issues/835
> feat: Allow plugins to be downloaded using a user `team_name` context

- managedplugin/download.go
GitHub now sometimes returns 302 on a HEAD
It seems to return 401 in tests. So we now do a GET and retry on 401/429.
Extracted from https://github.com/cloudquery/plugin-pb-go/pull/170
> fix: GitHub downloader should do a GET and retry, trying to discover the correct URL

- .github/workflows/lint_golang.yml
- .golangci.yml
- go.mod
- managedplugin/download.go
- managedplugin/plugin.go
- managedplugin/registry_test.go
- specs/destination.go
- specs/destination_test.go
- specs/registry.go
- specs/registry_test.go
- specs/source.go
- specs/source_test.go
Extracted from https://github.com/cloudquery/plugin-pb-go/pull/170
> fix: Quality of life improvements

- managedplugin/docker.go
This way we can make sure the user doesn't get confusing error messages like:
> error parsing HTTP 400 response body: no error details found in HTTP response body: "{"message":"parameter \"X-Meta-User-Team-Name\" in header has an error: empty value is not allowed","status":400}
or
> unknown: The server could not parse your request body
> fix(docker): Check for team and login before proceeding with docker registry download

- .github/workflows/unittest.yml
- managedplugin/download.go
- managedplugin/download_test.go
- managedplugin/hub.go
- managedplugin/options.go
- managedplugin/plugin.go
- managedplugin/plugin_test.go
This change allows Docker plugins to use the CloudQuery registry, meaning that configs can now be written like:
```
path: cloudquery/typeform
version: v1.2.3
```
instead of
```
registry: docker
path: docker.cloudquery.io/cloudquery/source-typeform:v1.2.3
```
The `docker` registry can still be used if preferred, either with or without the `docker.cloudquery.io` path.
> feat: Allow use of CloudQuery registry with docker plugins

- managedplugin/plugin.go
Fixes https://github.com/cloudquery/cloudquery/issues/16648
Also: https://github.com/cloudquery/cloudquery-issues/issues/1016
> fix: Tolerate non-JSON log lines from plugin

- managedplugin/plugin.go
This change allows callers of managedplugin to optionally pass in an `Environment` array, which, if used, will replace the default os.Environ for the created plugin.
The idea is that we will use this from the CLI to isolate plugin environment from one another. The core logic of how exactly that happens will stay in the CLI.
> feat: Allow managedplugins to control their environment

- managedplugin/docker.go
- managedplugin/plugin.go
- managedplugin/plugin_test.go
It seems every time we update the Go Docker SDK it forces users to update their local docker installation too due to API compatibility.
For example the current client version we use is `1.44` but GitHub Actions run on `1.43` so publishing fails:
https://github.com/cloudquery/cloudquery/actions/runs/8155813989/job/22292120213#step:12:12
---
> fix: Enable docker API negotiation

- managedplugin/docker.go
- managedplugin/download.go
- managedplugin/download_test.go
- managedplugin/options.go
- managedplugin/plugin.go
Adds option to skip using progressbar. Since the new progressbar release, writing to the progressbar where the target writer is closed (in our case, `os.Stdout`) produces an error.
> fix: Progressbar handling

- go.mod
- go.sum
This reverts commit cf33df6058bcab8052d43039abf91b94857c0daf.
https://github.com/cloudquery/plugin-pb-go/pull/330 introduced some regressions in our CLI (see 0)
---
> fix: Revert "fix(deps): Update module github.com/schollz/progressbar/v3 to v3.14.3 (#330)"

- managedplugin/download.go
- managedplugin/download_test.go
- managedplugin/metrics.go
- managedplugin/plugin.go
Still need to test this. Might not be the cleanest approach.
This should allow the CLI to report plugin downloads
Happy to rename the enum, couldn't think of a better one
---
> feat: Expose if plugin was downloaded or cached

- go.mod
- go.sum
Reverts cloudquery/plugin-pb-go#353
Until https://github.com/cloudquery/cloudquery-issues/issues/2041 is fixed
> fix: Revert "fix(deps): Update module github.com/docker/docker to v27"

- managedplugin/logging.go
Part of https://github.com/cloudquery/cloudquery/issues/18443. Both CLI and plugins add the invocation ID field to the log.
When the CLI invokes plugins it streams their logs into its own log so it all shows up in the same file.
This happens here https://github.com/cloudquery/plugin-pb-go/blob/28fae3fab7dd225622fdea542ae67ee5649e8b8c/managedplugin/plugin.go#L480
We parse the log line as JSON, then log it with the CLI logger.
`zerolog` doesn't remove duplicate fields (see https://github.com/rs/zerolog?tab=readme-ov-file#field-duplication ) we need to remove the duplicate ourselves (similar to `level`).
Please note that the duplicates only show up when passing `--log-format json` as it seems the text format does remove duplicates (`zerolog` saves the message to be printed internally in JSON …
> fix: Delete `invocation_id` log field when streaming plugins logs

- managedplugin/plugin.go
The usual pattern in go is to do `if err != nil { // do something }`.
The current code is a bit confusing to read as it does `if err == nil { return err }`.
A smaller change can be to do `if err == nil { return nil }`
---
> refactor: Early return in case of a connection error

- managedplugin/plugin.go
Fixes https://github.com/cloudquery/cloudquery-issues/issues/2280 (internal issue).
Sometimes plugins fail to launch the first time (we're not sure why, seems to be happening only on MacOS and for large plugins).
Retrying the same binary works, so this PR implements that.
Example logs:
```
2024-08-26T08:48:08Z INF Loading spec(s) args=["examples/aws-postgres.yml"] invocation_id=4356ddcc-f66d-4231-bdcd-90d4e803adb5 module=cli
2024-08-26T08:48:08Z DBG starting plugin attempt=1 invocation_id=4356ddcc-f66d-4231-bdcd-90d4e803adb5 module=cli path=******
2024-08-26T08:48:13Z INF Plugin server listening address=/var/folders/9s/pgf_fjl160j81k95zb5gm7vw0000gn/T/cq-VIAmPPIOcYreNayw.sock invocation_id=4356ddcc-f66d-4231-bdcd-90d4e803adb5 module=cli
2024-08-26T08:48:13Z DBG failed to start plugin, …
```
> fix: Attempt to launch plugin up to 3 times

- managedplugin/download.go
- managedplugin/plugin.go
Prerequisite to fully implement: https://github.com/cloudquery/cloudquery/issues/19286
In order to let CLI users when the plugins they are using are not up to date, we need to now what the latest version is.
This PR only adds this functionality within `plugin-pb-go` within the `managedplugin` module, but it isn't yet used, nor compared to the user's plugin version.
Sample check on CLI to see if it works:
```
$ go run . test-connection /Users/mariano.gappa/Code/test-aws-sync/all.yml
Loading spec(s) from /Users/mariano.gappa/Code/test-aws-sync/all.yml
You chose version v27.23.0. Latest version is v27.23.1.
```
Also note that this implementation errors in a lot of cases, but it is not the intention to actually error to the client; since the purpose is to show a warning, we'll probably elide …
> feat: Implement API to get latest plugin version.

- go.mod
- go.sum
This reverts commit b96b6da6b1e807690d4e6e532b29a777bf8f3746.
Looks like this dep update created a data race in the CLI CI so reverting it https://github.com/cloudquery/cloudquery/actions/runs/11330338120/job/31507943884?pr=19381#step:6:2468
Seems like they tried to fix it here https://github.com/schollz/progressbar/pull/202 but might have missed some cases
---
> fix: Revert "fix(deps): Update module github.com/schollz/progressbar/v3 to v3.16.1 (#410)"

- go.mod
- go.sum
- managedplugin/plugin.go
- managedplugin/version_checker.go
- managedplugin/version_checker_test.go
The previous iteration of this PR (https://github.com/cloudquery/plugin-pb-go/pull/415) had some non-ideal feedback:
- It might require a CLI login unnecessarily.
- Uses a brand new semver strategy, instead of using the one we use in the backend.
This implementation makes sure to not use any auth, and reuses the SemVer library we already use (although not in this repo).
It also warns already, rather than sending the version to the client for bespoke warnings, making it more lightweight for the client. Example use should be:
```
versionWarner, err := managedplugin.NewPluginVersionWarner(logger)
if err != nil {
// Could decide to ignore this error
}
didWarn, err := versionWarner.WarnIfOutdated(ctx, "cloudquery", "aws", usingVersion)
// Ignore both return values, since warning should be best …
```
> feat: Implement PluginVersionWarner to warn on outdated plugins.

- managedplugin/logging.go
- managedplugin/plugin.go
Fixes https://github.com/cloudquery/cloudquery-issues/issues/2624 (internal issue)
We were using the logger created here https://github.com/cloudquery/cloudquery/blob/69143a73499660db2ab714781a5d207884fb9303/cli/cmd/logging.go#L51 to output logs messages from plugins. Plugins already set their log context in https://github.com/cloudquery/plugin-sdk/blob/8b9e067af19604d90d2e77d6e1aff1d93adad752/plugin/plugin.go#L213 and https://github.com/cloudquery/plugin-sdk/blob/8b9e067af19604d90d2e77d6e1aff1d93adad752/plugin/plugin.go#L241, so when we stream them to the `cloudquery.log` file we should use a new logger with an empty context.
---
> fix: Reset logger context when streaming logs from plugins
